apiVersion: apps/v1
kind: Deployment
metadata:
  name: swarmos-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swarmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: swarmos
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "swarmos.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      serviceAccountName: swarmos-frontend
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: frontend
          image: {{ include "swarmos.image" (dict "img" .Values.image.frontend) | quote }}
          imagePullPolicy: {{ .Values.image.frontend.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
            - name: SWARM_ENV
              value: prod
            - name: NEXT_PUBLIC_API_URL
              value: {{ printf "https://%s/api" .Values.ingress.host | quote }}
            - name: NEXT_PUBLIC_WS_URL
              value: {{ printf "wss://%s/ws/telemetry" .Values.ingress.host | quote }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
          livenessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet: { path: /, port: http }
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1001
            runAsGroup: 1001
            capabilities:
              drop: [ALL]
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 32Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: swarmos-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "swarmos.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
