#!/usr/bin/env bash
# Phase 6.C — bootstrap a local dev auth environment.
#
# Idempotent. Creates:
#   - `SWARM_JWT_SECRET=<32-byte hex>` in .env (preserves existing value)
#   - `infra/config/operators.yaml` with three local accounts:
#       op-viewer01    role=viewer
#       op-operator01  role=operator
#       op-commander01 role=commander  (with a fresh TOTP secret)
#     All three share password `swarm-dev`.
#
# Prints the commander's `otpauth://` URI so you can scan it into a TOTP
# authenticator (Aegis / 1Password / FreeOTP). The secret is also written
# to `infra/config/operators.yaml.commander-totp.txt` for one-time pickup
# — delete it after enrolment.
#
# NEVER use this for staging / production. The drone-day checklist §2.C
# walks the real provisioning flow.

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

if [ ! -d .venv ]; then
  echo "[bootstrap-auth] .venv not found — run \`make setup-python\` first" >&2
  exit 1
fi

ENV_FILE=".env"
OPS_FILE="${SWARM_OPERATORS_CONFIG:-infra/config/operators.yaml}"
TOTP_DUMP="${OPS_FILE}.commander-totp.txt"
DEV_PASSWORD="${SWARM_DEV_PASSWORD:-swarm-dev}"

if [ ! -f "$ENV_FILE" ]; then
  cp .env.example "$ENV_FILE"
  echo "[bootstrap-auth] created .env from .env.example"
fi

# 1) JWT secret — generate iff blank.
if grep -qE '^SWARM_JWT_SECRET=\s*$' "$ENV_FILE" || ! grep -q '^SWARM_JWT_SECRET=' "$ENV_FILE"; then
  SECRET=$(.venv/bin/python -c 'import secrets;print(secrets.token_hex(32))')
  if grep -q '^SWARM_JWT_SECRET=' "$ENV_FILE"; then
    # `sed -i` portability across BSD/GNU: write through a backup, then drop it.
    sed -i.bak "s|^SWARM_JWT_SECRET=.*$|SWARM_JWT_SECRET=${SECRET}|" "$ENV_FILE"
    rm -f "${ENV_FILE}.bak"
  else
    printf '\n# Phase 6.C dev secret — regenerate with `make bootstrap-auth-dev` if leaked.\nSWARM_JWT_SECRET=%s\n' "$SECRET" >> "$ENV_FILE"
  fi
  echo "[bootstrap-auth] generated SWARM_JWT_SECRET (32 bytes) in $ENV_FILE"
else
  echo "[bootstrap-auth] SWARM_JWT_SECRET already set in $ENV_FILE — left untouched"
fi

# 2) Operators YAML — create iff missing. Never overwrite a real file.
if [ -e "$OPS_FILE" ]; then
  echo "[bootstrap-auth] $OPS_FILE already exists — left untouched"
  exit 0
fi

mkdir -p "$(dirname "$OPS_FILE")"

PW_HASH=$(.venv/bin/python -m backend.app.auth.cli hash-password "$DEV_PASSWORD")
# `new-mfa` prints three lines; we want both the BASE32 secret and the URI.
MFA_OUT=$(.venv/bin/python -m backend.app.auth.cli new-mfa op-commander01)
MFA_SECRET=$(echo "$MFA_OUT" | awk -F': *' '/mfa_secret/ {print $2}')
MFA_URI=$(echo   "$MFA_OUT" | awk -F': *' '/otpauth uri/ {print $2}')

cat > "$OPS_FILE" <<YAML
# SwarmOS operator identity store — LOCAL DEV ONLY.
# Generated by scripts/bootstrap_auth_dev.sh. Do not deploy.
# Password for all three accounts: ${DEV_PASSWORD}
# Regenerate with: rm ${OPS_FILE} && make bootstrap-auth-dev

operators:
  - operator_id: op-viewer01
    password_hash: "${PW_HASH}"
    role: viewer

  - operator_id: op-operator01
    password_hash: "${PW_HASH}"
    role: operator

  - operator_id: op-commander01
    password_hash: "${PW_HASH}"
    role: commander
    mfa_secret: "${MFA_SECRET}"
YAML

# Write the TOTP URI to a side file so the operator can pick it up once.
cat > "$TOTP_DUMP" <<TOTP
operator_id : op-commander01
mfa_secret  : ${MFA_SECRET}
otpauth uri : ${MFA_URI}

Scan the URI above into a TOTP authenticator (Aegis / 1Password /
FreeOTP / Google Authenticator). Delete this file after enrolment.
TOTP

echo "[bootstrap-auth] wrote $OPS_FILE (viewer / operator / commander all share password \"${DEV_PASSWORD}\")"
echo "[bootstrap-auth] commander TOTP URI written to $TOTP_DUMP"
echo ""
echo "  Login as viewer:    op-viewer01    / ${DEV_PASSWORD}"
echo "  Login as operator:  op-operator01  / ${DEV_PASSWORD}"
echo "  Login as commander: op-commander01 / ${DEV_PASSWORD} + TOTP (see ${TOTP_DUMP})"
