"""Render and record the causal Take C dev replay at the YC viewport.

The replay source must already have been generated by
``scripts/capture_causal_take_c_truth.py``. This script never edits runtime
truth. It selects presentation timestamps from capture milestones, screenshots
the rendered Console, and records one real-time playback of those captured
frames.
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
import shutil
from pathlib import Path
from typing import Any
from urllib.parse import urlencode, urlparse

from playwright.async_api import Page, Response, async_playwright

PLAYBACK_SCALE = 4
VIEWPORT = {"width": 2560, "height": 1440}


def _sample_times(capture: dict[str, Any]) -> dict[str, int]:
    milestones = capture["milestones"]

    def midpoint(a: str, b: str) -> int:
        return round((int(milestones[a]) + int(milestones[b])) / 2)

    return {
        "composition": midpoint("composition_at_ms", "capacity_available_at_ms"),
        "reinforced": midpoint("reinforcement_converged_at_ms", "failure_at_ms"),
        "replacement": min(
            int(capture["duration_ms"]),
            int(milestones["replacement_converged_at_ms"]) + 150,
        ),
        "verified": min(
            int(capture["duration_ms"]),
            int(milestones["anomaly_verified_at_ms"]) + 100,
        ),
    }


def _replay_url(base_url: str, capture_at_ms: int, *, controls: bool) -> str:
    query = urlencode(
        {
            "take": "c",
            "at": capture_at_ms * PLAYBACK_SCALE,
            "replay": "0",
            "controls": "1" if controls else "0",
        }
    )
    return f"{base_url.rstrip('/')}/dev/replay?{query}"


def _system_chromium() -> str:
    executable = shutil.which("chromium") or shutil.which("google-chrome")
    if executable is None:
        raise RuntimeError(
            "GitHub runner does not expose a system Chromium/Chrome executable"
        )
    return executable


def _known_nonfatal_resource(error: dict[str, str | int]) -> bool:
    parsed = urlparse(str(error["url"]))
    if parsed.hostname == "server.arcgisonline.com":
        return True
    return (
        parsed.hostname in {"localhost", "127.0.0.1"}
        and parsed.path == "/favicon.ico"
    )


def _record_response(
    response: Response,
    resource_errors: list[dict[str, str | int]],
) -> None:
    if response.status >= 400:
        resource_errors.append({"status": response.status, "url": response.url})


async def _wait_surface(page: Page) -> None:
    await page.wait_for_selector('[data-testid="console-surface"]', timeout=30_000)
    await page.wait_for_selector('[data-testid="mission-authority"]', timeout=30_000)
    await page.wait_for_timeout(500)


async def _select_intrusion(page: Page) -> None:
    """Pin the already-rendered intrusion objective through the real UI control."""
    button = page.get_by_role(
        "button",
        name=re.compile(r"\bINTRUSION\b", re.IGNORECASE),
    ).first
    await button.wait_for(state="visible", timeout=10_000)
    await button.click()


async def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--capture",
        default="frontend/public/dev/take-c-causal-sim.json",
    )
    parser.add_argument("--output", default="artifacts/take-c-visual")
    parser.add_argument("--url", default="http://localhost:3000")
    args = parser.parse_args()

    capture_path = Path(args.capture)
    source = await asyncio.to_thread(capture_path.read_text, encoding="utf-8")
    capture = json.loads(source)
    if capture.get("provenance") != "causal-simulator-runtime":
        raise RuntimeError("visual capture source is not a causal simulator runtime capture")
    proof_scope = capture.get("proof_scope", {})
    if proof_scope.get("px4_disposition_claim") is not False:
        raise RuntimeError("visual capture must preserve simulator-only disposition scope")

    output = Path(args.output)
    await asyncio.to_thread(output.mkdir, parents=True, exist_ok=True)
    sample_times = _sample_times(capture)
    console_errors: list[str] = []
    page_errors: list[str] = []
    resource_errors: list[dict[str, str | int]] = []
    screenshots: dict[str, str] = {}

    async with async_playwright() as playwright:
        browser = await playwright.chromium.launch(
            headless=True,
            executable_path=_system_chromium(),
        )
        context = await browser.new_context(viewport=VIEWPORT, device_scale_factor=1)
        page = await context.new_page()
        page.on(
            "console",
            lambda message: console_errors.append(message.text)
            if message.type == "error"
            else None,
        )
        page.on("pageerror", lambda error: page_errors.append(str(error)))
        page.on(
            "response",
            lambda response: _record_response(response, resource_errors),
        )

        for label, capture_at_ms in sample_times.items():
            await page.goto(
                _replay_url(args.url, capture_at_ms, controls=False),
                wait_until="networkidle",
            )
            await _wait_surface(page)
            await _select_intrusion(page)
            await page.wait_for_timeout(500)
            screenshot = output / f"take-c-{label}.png"
            await page.screenshot(path=str(screenshot), full_page=False)
            screenshots[label] = str(screenshot)

        await context.close()

        video_dir = output / "video"
        await asyncio.to_thread(video_dir.mkdir, exist_ok=True)
        video_context = await browser.new_context(
            viewport=VIEWPORT,
            device_scale_factor=1,
            record_video_dir=str(video_dir),
            record_video_size=VIEWPORT,
        )
        video_page = await video_context.new_page()
        video_page.on(
            "console",
            lambda message: console_errors.append(message.text)
            if message.type == "error"
            else None,
        )
        video_page.on("pageerror", lambda error: page_errors.append(str(error)))
        video_page.on(
            "response",
            lambda response: _record_response(response, resource_errors),
        )
        await video_page.goto(
            _replay_url(args.url, 0, controls=True),
            wait_until="networkidle",
        )
        await _wait_surface(video_page)
        await video_page.get_by_role("button", name="PLAY").click()
        await _select_intrusion(video_page)
        await video_page.locator('[data-testid="replay-controls"]').evaluate(
            "element => { element.style.display = 'none'; }"
        )
        await video_page.wait_for_timeout(
            int(capture["duration_ms"]) * PLAYBACK_SCALE + 1_000
        )
        video = video_page.video
        await video_page.close()
        await video_context.close()
        if video is None:
            raise RuntimeError("Playwright did not create a Take C video")
        recorded_path = Path(await video.path())
        final_video = output / "take-c-causal-runtime.webm"
        await asyncio.to_thread(shutil.copy2, recorded_path, final_video)
        await browser.close()

    nonfatal_resource_errors = [
        error for error in resource_errors if _known_nonfatal_resource(error)
    ]
    fatal_resource_errors = [
        error for error in resource_errors if not _known_nonfatal_resource(error)
    ]
    resource_console_errors = [
        error
        for error in console_errors
        if error.startswith("Failed to load resource:")
    ]
    fatal_console_errors = [
        error
        for error in console_errors
        if not error.startswith("Failed to load resource:")
    ]

    manifest = {
        "source": str(capture_path),
        "provenance": capture["provenance"],
        "proof_scope": proof_scope,
        "world_facts": capture["world_facts"],
        "milestones": capture["milestones"],
        "playback_scale": PLAYBACK_SCALE,
        "viewport": VIEWPORT,
        "samples_capture_ms": sample_times,
        "screenshots": screenshots,
        "video": str(final_video),
        "console_errors": console_errors,
        "page_errors": page_errors,
        "resource_errors": resource_errors,
        "nonfatal_resource_errors": nonfatal_resource_errors,
        "resource_console_warnings": resource_console_errors,
    }
    payload = json.dumps(manifest, indent=2) + "\n"
    await asyncio.to_thread(
        (output / "manifest.json").write_text,
        payload,
        encoding="utf-8",
    )

    if page_errors or fatal_console_errors or fatal_resource_errors:
        raise RuntimeError(
            "browser errors during Take C capture: "
            f"page={page_errors} console={fatal_console_errors} "
            f"resources={fatal_resource_errors}"
        )


if __name__ == "__main__":
    asyncio.run(main())
